name: Deploy instagram-mern frontend

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t trituong/insta-frontend .
      - name: Publish Image to docker hub
        run: docker push trituong/insta-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull trituong/insta-frontend
      - name: Delete old container
        run: docker rm -f insta-fe-container
      - name: Run docker container
        run: docker run -d -p 3000:80 --name insta-fe-container trituong/insta-frontend